name: PingSpot_prod

services:
  pingspot-redis:
    image: redis:latest
    container_name: pingspot_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - pingspot_redis_data:/data
    networks:
      - pingspot_network

  pingspot-postgres:
    image: postgis/postgis:15-3.4
    container_name: pingspot_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRE_DB}
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
    ports:
      - "${POSTGRE_PORT}:5432"
    env_file:
      - .env
    volumes:
      - pingspot_postgre_data:/var/lib/postgresql/data
    networks:
      - pingspot_network

  pingspot-mongodb:
    image: mongo:latest
    container_name: pinspot_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - pingspot_mongodb_data:/data/db
    networks:
      - pingspot_network

networks:
  pingspot_network:

volumes:
  pingspot_redis_data:
  pingspot_postgre_data:
  pingspot_mongodb_data:
